### ISSUE TITLE
Container not starting, Docker Healthcheck failed

### ISSUE THREAD

**Issue by duckietm** [madnuttah/unbound-docker#20]
i am using the latest docker image but it now has problems with starting the docker, it is running as it accepts requests:

madnuttah/unbound:latest                       "/usr/local/sbin/unb…"   3 minutes ago   Up 13 seconds (health: starting)   0.0.0.0:5335->5335/tcp, 0.0.0.0:5335->5335/udp, :::5335->5335/tcp, :::5335->5335/udp

my docker-compose.yml

```
unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    hostname: unbound
    networks:
      dns-network:
        ipv4_address: 172.22.0.2
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    environment:
      TZ: "Europe/Amsterdam"
    volumes:
      - ./unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw #Your local path to Unbound
      - ./unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - ./unbound/log.d/:/usr/local/unbound/log.d/:rw
      - ./unbound/zones.d/:/usr/local/unbound/zones.d/:rw
      - ./unbound/certs.d/:/usr/local/unbound/certs.d/:rw
      - ./unbound/iana.d/:/usr/local/unbound/iana.d/:rw
    restart: unless-stopped
```

**Comment by duckietm** [comment]
![image](https://user-images.githubusercontent.com/1917443/213269095-dd7c037b-ee7c-4aa7-bc6d-bc18a4d66811.png)

**Comment by madnuttah** [comment]
Your compose is fine. Make sure the following is set in your unbound.conf: 

`access-control: 127.0.0.0/8 allow`
`interface: 127.0.0.1@53`

**Comment by duckietm** [comment]
Ah but the problem is, we run unbound on port 5335
How do we change the check ?

**Comment by madnuttah** [comment]
The healthcheck is done on the loopback interface on port 53 by periodic nslookups on internic.net. Unbound should resolve like so. Is the container still unhealthy?

**Comment by duckietm** [comment]
yes, as we bridge the connection and therefor are not able to use 53 as ubuntu server is already using this port
That is why Pi-Hole also recommend to use port 5335

**Comment by duckietm** [comment]
https://docs.pi-hole.net/guides/dns/unbound/

**Comment by madnuttah** [comment]
You can disable the healthcheck in your docker compose:

```
unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    hostname: unbound
    networks:
      dns-network:
        ipv4_address: 172.22.0.2
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    environment:
      TZ: "Europe/Amsterdam"
    volumes:
      - ./unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw #Your local path to Unbound
      - ./unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - ./unbound/log.d/:/usr/local/unbound/log.d/:rw
      - ./unbound/zones.d/:/usr/local/unbound/zones.d/:rw
      - ./unbound/certs.d/:/usr/local/unbound/certs.d/:rw
      - ./unbound/iana.d/:/usr/local/unbound/iana.d/:rw
    restart: unless-stopped
    healthcheck:
      disable: true
```
