### ISSUE TITLE
Container cannot start, missing elements

### ISSUE THREAD

**Issue by zilexa** [madnuttah/unbound-docker#24]
**Describe the bug**
 The container cannot start: 
```
/usr/local/sbin/unbound.sh: line 2: /usr/local/unbound/unbound.d/sbin/unbound-anchor: not found
/usr/local/sbin/unbound.sh: exec: line 3: /usr/local/unbound/unbound.d/sbin/unbound: not found
```

**To Reproduce**
docker compose: 
```
  dns-unbound:
    container_name: dns-unbound
    image: madnuttah/unbound:latest
    hostname: dns-unbound
    restart: always
    network_mode: host
    volumes: 
      - $DOCKERDIR/unbound:/usr/local/unbound
```

**Expected behavior**
Container should start normally. 

**Screenshots**

**Please complete the following information:**
 - Device: homeserver situation, Manjaro Gnome (Arch based). x86-64. 

**Additional context**
I would like to run it in network_mode:host for now, but that doesn't matter, it is missing key parts of unbound. 
Unbound.conf: https://pastebin.com/GHpj1L8D but I don't think it has reached the point where conf is being loaded..
