### ISSUE TITLE
Docker-compose not working

### ISSUE THREAD

**Issue by kieranlittle667** [madnuttah/unbound-docker#33]
Hi,
When I run the command with 
```
docker run --name madnuttah-unbound -d \
-p 5335:5335/udp \
-p 5335:5335/tcp \
--restart=unless-stopped \
madnuttah/unbound:latest

```It works and I am able to look up addresses from another machine using the unbound machine's address and port 5335 however when I use my docker-compose file I am unable to. Pihole works fine, and I can browse to my pihole IP etc.

```
version: '2'

services:
  pihole:
    container_name: pi-hole
    image: pihole/pihole:latest
    hostname: pi-hole
    domainname: solingen.local
    depends_on:
      - unbound
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    networks:
      dns-network:
        ipv4_address: 172.20.0.2
    dns:
      - 172.20.0.3
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      ServerIP: 192.168.100.211
      VIRTUAL_HOST: pi-hole-vm.solingen.local
      WEBPASSWORD: '*P@ssw0rd_Pihole*'
      TZ: Europe/London
      CORS_HOSTS: solingen.local
      PIHOLE_DNS_: 172.20.0.3#5335
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      REV_SERVER: "true"
      REV_SERVER_TARGET: 192.168.100.220
      REV_SERVER_DOMAIN: solingen.local
      REV_SERVER_CIDR: 192.168.100.0/24
    volumes:
      - /home/klittle/pihole/pihole:/etc/pihole:rw
      - /home/klittle/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    hostname: unbound
    domainname: solingen.local
    ports:
      - 192.168.100.211:5335:5335/tcp
      - 192.168.100.211:5335:5335/udp
    networks:
      dns-network:
        ipv4_address: 172.20.0.3

    environment:
      TZ: Europe/London
      ServerIP: 192.168.100.211
      VIRTUAL_HOST: unbound_vm.solingen.local
    volumes:
      - /home/klittle/unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw
      - /home/klittle/unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - /home/klittle/unbound/iana.d/:/usr/local/unbound/iana.d/:rw
      - /home/klittle/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - /home/klittle/unbound/zones.d/:/usr/local/unbound/zones.d/:rw
    restart: unless-stopped

networks:
  dns-network:
    driver: bridge
    driver_opts:
      parent: ent3
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

I tried following [this guide](https://www.xfelix.com/2020/09/pihole-unbound-docker-setup-on-raspberry-pi/) and my config files look the same but still nothing.
Anything else I can try? There aren't any logs from the container so I'm assuming that means it's startying up fine.
Thanks

**Comment by madnuttah** [comment]
Hello and thanks for contacting me.

It's hard to analyze your compose file, you can keep the formatting when using ``` before and after your yaml code.

If I remember correctly, I had issues too not using a /16 subnet mask for the bridge network (I guess need to fix this in my example, sorry for that):

```
...
# Indentations may not be correct 
networks:
  dns-network:
    driver: bridge
    driver_opts:
      parent: ent3
    ipam:
      config:
        - subnet: 172.20.0.0/16 #try this instead of /24
        gateway: 172.20.0.1
```

Other than that, can you put your unbound ports like so:

```
...
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    hostname: unbound
    domainname: solingen.local
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    networks:
      dns-network:
        ipv4_address: 172.20.0.3
...
```

**Comment by kieranlittle667** [comment]
Hi,
Thanks so much for replying. I tried the /16 network and the adjusted port mapping syntax and it still didn't work.
I then tried running with a host network instead and it still didn't work.

```
    docker run -d \
      --name unbound \
      --hostname unbound \
      --domainname solingen.local \
      --network host \
      --env TZ=Europe/London \
      --env ServerIP=192.168.100.211 \
      --env VIRTUAL_HOST=unbound_vm.solingen.local \
      -v /home/klittle/unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw \
      -v /home/klittle/unbound/conf.d/:/usr/local/unbound/conf.d/:rw \
      -v /home/klittle/unbound/iana.d/:/usr/local/unbound/iana.d/:rw \
      -v /home/klittle/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw \
      -v /home/klittle/unbound/zones.d/:/usr/local/unbound/zones.d/:rw \
      --restart unless-stopped \
      madnuttah/unbound:latest

```
I think there's 2 separate issues here as if I nmap TCP port 5335 while the container is running in host mode the port is open, but I can't resolve a domain with it, however if I run with my bridged network UDP 5335 is open, but tcp 5335 shows as closed. If I run your default command as above with no volumes or variables I can resolve hostnames, and nmap -p 5335 shows the tcp port as open.

**Comment by madnuttah** [comment]
My pleasure!

Could you show me your unbound.conf please? ANd is there a firewall or apparmor active on your docker host?

**Comment by kieranlittle667** [comment]
```
root@piholeVM:/home/klittle# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:5335
ACCEPT     udp  --  anywhere             172.17.0.2           udp dpt:5335

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
root@piholeVM:/home/klittle# ufw status
Status: inactive
root@piholeVM:/home/klittle# cat unbound/unbound.conf
include: "/usr/local/unbound/conf.d/*.conf"
include: "/usr/local/unbound/zones.d/*.conf"

server:
        module-config: "validator iterator"
        username: "_unbound"
    directory: "/usr/local/unbound"
        chroot: "/usr/local/unbound"
        do-daemonize: no
        tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt
root@piholeVM:/home/klittle#
```
I've attached my entire unbound dir
REMOVED

**Comment by madnuttah** [comment]
I wasn't sure if there were sensitive content in that zip file so I removed it.

I can see an issue with permissions in your log: ```fatal error: could not open autotrust file for writing, /iana.d/root.key.1-1-7f7abfe46790: Permission denied```. Please fix the permissions and ownership in your `iana.d` folder, the container won't spin up otherwise. 

It is also possible that iptables blocks access to the internal IPv4 172.20.0.3 as I see only 172.17.0.2. Could you add rules for testing, please?

Here's an adapted security.conf for your environment:

```
server:	
    do-not-query-localhost: no
	
    unblock-lan-zones: no
    insecure-lan-zones: yes
	
    private-domain: "solingen.local."
    private-domain: "100.168.192.in-addr.arpa."
	
    domain-insecure: "solingen.local."
    domain-insecure: "100.168.192.in-addr.arpa."
    private-address: 10.0.0.0/8
    private-address: 172.16.0.0/12
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: fd00::/8
    private-address: fe80::/10
    private-address: ::ffff:0:0/96
	
    hide-identity: yes
    identity: "server"
    hide-version: yes
    version: ""    
    aggressive-nsec: yes
    qname-minimisation: yes
    qname-minimisation-strict: no	
    disable-dnssec-lame-check: no
    hide-trustanchor: yes
    harden-algo-downgrade: yes
    harden-below-nxdomain: yes
    harden-dnssec-stripped: yes
    harden-glue: yes
    harden-large-queries: yes
    harden-referral-path: yes
    harden-short-bufsize: yes
    minimal-responses: yes
    deny-any: yes
    use-caps-for-id: yes
    val-clean-additional: yes
    val-max-restart: 5
    root-key-sentinel: yes
    zonemd-permissive-mode: no

```
