### ISSUE TITLE
[Bug] container unable to start without providing ubound.conf

### ISSUE THREAD

**Issue by cacula** [madnuttah/unbound-docker#51]
**Describe the bug**
After the 1.19.1-0 update the container does not start anymore and gets into a crash loop. following error appears in the logs:
```
[1707896685] unbound[1:0] error: can't bind socket: Address not available for ::1 port 53
[1707896685] unbound[1:0] fatal error: could not open ports
```
**To Reproduce**
Use latest version with following compose file
```
  unbound:
    container_name: unbound
    hostname: unbound
    image: madnuttah/unbound:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 50m
    ports:
      - "127.0.0.1:5335:5335/tcp"
      - "127.0.0.1:5335:5335/udp"
    networks:
      - dns
    environment:
      TZ: Europe/Berlin
```
**Expected behavior**
container should start as it did before the update

**Workaround**
Download "default" unbound.conf from [https://github.com/madnuttah/unbound-docker/blob/main/unbound/root/usr/local/unbound/unbound.conf ](https://github.com/madnuttah/unbound-docker/blob/main/unbound/root/usr/local/unbound/unbound.conf ) and add it to the compose file:
```
  unbound:
    container_name: unbound
    hostname: unbound
    image: madnuttah/unbound:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 50m
    ports:
      - "127.0.0.1:5335:5335/tcp"
      - "127.0.0.1:5335:5335/udp"
    networks:
      - dns
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./unbound.conf:/usr/local/unbound/unbound.conf:rw
```
**Please complete the following information:**
 - Device: VM
 - OS: Debian Bookworm
 - Architecture: amd64
 - Version: latest

**Comment by madnuttah** [comment]
Hi and thanks for opening a new issue. Take a look at your config files. Do a quick search for "53" and comment out those lines. The image is way more secure now because unbound runs in a pretty limited user context. You would need to set capacities in your docker compose if you insist in using port 53.

Would you mind showing your configs without sensitive information? I'll take a look then, there are maybe more entries to adapt. Thank you.

**Comment by cacula** [comment]
that's my complete docker compose
```
# https://github.com/pi-hole/docker-pi-hole
# https://github.com/madnuttah/unbound-docker
version: "3"

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: jacklul/pihole:latest
    restart: unless-stopped
    depends_on:
      - unbound
    deploy:
      resources:
        limits:
          memory: 250m
    ports:
      - "192.168.1.254:53:53/tcp"
      - "192.168.1.254:53:53/udp"
    networks:
      - traefik
      - dns
    environment:
      TZ: Europe/Berlin
      FTLCONF_LOCAL_IPV4: 192.168.1.254
      PIHOLE_DNS_: unbound#5335
      REV_SERVER: true
      REV_SERVER_DOMAIN: xxx
      REV_SERVER_TARGET: 192.168.1.1
      REV_SERVER_CIDR: 10.8.0.0/16
      WEBTHEME: default-auto
      DNSMASQ_LISTENING: all
    volumes:
       - etc:/etc/pihole/
       - dnsmasq_d:/etc/dnsmasq.d/
       - updatelists:/etc/pihole-updatelists/
       - ./pihole-updatelists.conf:/etc/pihole-updatelists/pihole-updatelists.conf
    labels:
       - traefik.enable=true
       - traefik.http.routers.pihole-ssl.rule=Host(`pihole.example.net`)
       - traefik.http.routers.pihole-ssl.entrypoints=websecure
       - traefik.http.routers.pihole-ssl.tls=true
       - traefik.http.routers.pihole-ssl.tls.certresolver=myresolver
       - traefik.http.routers.pihole-ssl.service=pihole-ui
       - traefik.http.routers.pihole.rule=Host(`pihole.example.net`)
       - traefik.http.routers.pihole.entrypoints=web
       - traefik.http.routers.pihole.service=pihole-ui
       - traefik.http.services.pihole-ui.loadbalancer.server.port=80
  unbound:
    container_name: unbound
    hostname: unbound
    image: madnuttah/unbound:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 50m
    ports:
      - "127.0.0.1:5335:5335/tcp"
      - "127.0.0.1:5335:5335/udp"
    networks:
      - dns
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./unbound.conf:/usr/local/unbound/unbound.conf:rw

volumes:
  etc:
  dnsmasq_d:
  updatelists:

networks:
  traefik:
    external: true
  dns:
```
as mentioned in the bug report, the following line I only had to add  as a workaround to get the container running again
```
    volumes:
      - ./unbound.conf:/usr/local/unbound/unbound.conf:rw
```
the unbound.conf I'm using for the workaround is just a fresh copy I downloaded from your repo - without any modifications: [https://github.com/madnuttah/unbound-docker/blob/main/unbound/root/usr/local/unbound/unbound.conf](https://github.com/madnuttah/unbound-docker/blob/main/unbound/root/usr/local/unbound/unbound.conf)
I just want to use Port 53 for pihole as it will serve as DNS on the local network.
