### ISSUE TITLE
Help with redis configuration and a persistent cachedb.d volume

### ISSUE THREAD

**Issue by jata1** [madnuttah/unbound-docker#55]
I have setup unbound on a macvlan and it starts fine and seems to be working. Today I have tried to add redis database so that records are cached persistently.

Good news is that I have got the docker/compose to start and but I am not sure if it is all working correctly.

How can I tell if redis database is working? Should I be able to view/see the database somewhere? Can I tell when the response comes from the redis database?

If I restart the unbound container, a new volume is created so I think this could be an issue. I think the same volume should be used across restarts of the container. Correct?

Here is my compose file. Anything stupid I have done?

`version: '3.3'

services:
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    networks:
      rpi5_macvlan:
        ipv4_address: "192.168.100.15"
    environment:
      ServerIP: 192.168.100.15
      TZ: ${TZ}
      UID: ${PUID}
      GID: ${PGID}
    volumes:
      - /symlinks/omv-system/appdata/unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw #Your local path to Unbound
      - /symlinks/omv-system/appdata/unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - /symlinks/omv-system/appdata/unbound/iana.d/:/usr/local/unbound/iana.d/:rw
      - /symlinks/omv-system/appdata/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - /symlinks/omv-system/appdata/unbound/zones.d/:/usr/local/unbound/zones.d/:rw
    volumes_from:
      - redis-socket:rw
    restart: unless-stopped
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s

  redis-socket:
    image: busybox
    container_name: redis-socket
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        chown -R 999:100 /usr/local/unbound/cachedb.d/ # Change group (:1000) to your used GID
        /bin/sh
    volumes:
       - /symlinks/omv-system/appdata/unbound/cachedb.d:/usr/local/unbound/cachedb.d/
      
  redis:
    container_name: unbound-db
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /symlinks/omv-system/appdata/unbound/redis.conf:/usr/local/etc/redis/redis.conf
    volumes_from:
      - redis-socket:rw

volumes:
  cachedb.d:

networks:
  rpi5_macvlan:
    name: rpi5_macvlan
    external: true`

**Comment by madnuttah** [comment]
Hello and thanks for contacting me.

If you put the file contents in leading and trailing ``` it's better readable.

In your compose this 

```
TZ: ${TZ}
UID: ${PUID}
GID: ${PGID}
```

looks off. It should be like this:

```
TZ: "Australia/Canberra"
UID: ${UID}
GID: ${GID}
```

Please change the timezone to your local [timezone](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

Answering your question:

You can verify the connection to redis in the log, there should read 

```
Feb 18 22:01:02 unbound[1:0] notice: init module 1: cachedb
Feb 18 22:01:02 unbound[1:0] notice: Redis initialization 
Feb 18 22:01:02 unbound[1:0] notice: Connection to Redis established
```

In Portainer you can also view the `cachedb.d` volume with a `redis.sock` file.

<img width="292" alt="image" src="https://github.com/madnuttah/unbound-docker/assets/96331755/7e0e0587-b940-42f7-a807-5e55697313af">

Thank you.

**Comment by jata1** [comment]
Thank you for your help - this is great work by the way - so thank you.

The environment variables are all fine and part of my OMV / nas setup.  They are updated/replaced when the compose file creates the container. 

I'm not getting any logs relating to redis at startup so I still have work to do to get this working. I put the cachedb.conf file into the conf.d folder which is probably not correct but I thought i would try that.

Trying to repost my compose file in the correct code brackets but it didn't work last time. 




```
version: '3.3'

services:
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    networks:
      rpi5_macvlan:
        ipv4_address: "192.168.100.15"
    environment:
      ServerIP: 192.168.100.15
      TZ: ${TZ}
      UID: ${PUID}
      GID: ${PGID}
    volumes:
      - /symlinks/omv-system/appdata/unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw #Your local path to Unbound
      - /symlinks/omv-system/appdata/unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - /symlinks/omv-system/appdata/unbound/iana.d/:/usr/local/unbound/iana.d/:rw
      - /symlinks/omv-system/appdata/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - /symlinks/omv-system/appdata/unbound/zones.d/:/usr/local/unbound/zones.d/:rw
    volumes_from:
      - redis-socket:rw
    restart: unless-stopped
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s

  redis-socket:
    image: busybox
    container_name: redis-socket
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        chown -R 999:100 /usr/local/unbound/cachedb.d/ # Change group (:1000) to your used GID
        /bin/sh
    volumes:
       - /symlinks/omv-system/appdata/unbound/cachedb.d:/usr/local/unbound/cachedb.d/
      
  redis:
    container_name: unbound-db
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /symlinks/omv-system/appdata/unbound/redis.conf:/usr/local/etc/redis/redis.conf
    volumes_from:
      - redis-socket:rw

volumes:
  cachedb.d:

networks:
  rpi5_macvlan:
    name: rpi5_macvlan
    external: true

``` ``

**Comment by by-carlos** [comment]
@jata1 I have a similar setup. I reckon you need the volume for the db.

Easiest way to confirm if is being used is running dbsize, it should start growing.

Below the compose.yaml I'm using, it might help:

```
services:
  redis-dns:
    container_name: redis-dns
    hostname: redis-dns
    image: redis:alpine
    environment:
      - PUID=1234 # user id
      - PGID=5678 # group id
      - TZ=Pacific/Auckland
    healthcheck:
      interval: 60s
      retries: 5
      start_period: 60s
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 3s
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    networks:
      bridge0:
        ipv4_address: 172.21.0.104
    restart: unless-stopped

  unbound:
    container_name: unbound
    depends_on:
        - redis-dns
    hostname: unbound
    image: madnuttah/unbound:latest
[...]
```

**Comment by jata1** [comment]
thanks @JaneDilbert

do you mean I am missing this volume?

` - ./redis/data:/data`

**Comment by jata1** [comment]
and can someone explain what this part is doing - I am not sure

```
volumes:
  cachedb.d:
```

**Comment by madnuttah** [comment]
Thanks @JaneDilbert ❤️

@jata1 You have put the log in a persistent volume, check `../log.d/unbound.log`.

If not, do you see log entries in the shell? `sudo docker logs unbound`?

The `volumes: cachedb.d:` is an alias set for the volume, otherwise an ugly string will be created and the volume ain't accessible using Portainer or such.

**Comment by jata1** [comment]
I do have the logs in a persistent volume - here are the startup log entries but nothing for redis

```
Feb 19 16:41:56 unbound[1:0] notice: init module 0: validator
Feb 19 16:41:56 unbound[1:0] notice: init module 1: iterator
Feb 19 16:41:56 unbound[1:0] info: start of service (unbound 1.19.1).

```

**Comment by jata1** [comment]
Thanks for the info on the cachedb.d alias for the volume - it's not working for me as I am getting the ugly string.

Is there somewhere specific I need to put the cachedb.conf file? Maybe that is part of the issue

**Comment by madnuttah** [comment]
It seems like you didn't set the `cachedb` entry in your `unbound.conf` as there is nothing to see that the module is loaded. Change your `module-config`like so:

`server: 
   module-config: "cachedb validator iterator"`

The order of the modules is important, cachedb has to be loaded before the iterator.

**Comment by by-carlos** [comment]
> thanks @JaneDilbert
> 
> do you mean I am missing this volume?
> 
> ` - ./redis/data:/data`

Yup.

**Comment by jata1** [comment]
progress...

```
Feb 19 19:30:27 unbound[1:0] notice: init module 0: cachedb
Feb 19 19:30:27 unbound[1:0] notice: Redis initialization
Feb 19 19:30:27 unbound[1:0] notice: Connection to Redis established
Feb 19 19:30:27 unbound[1:0] notice: Connection to Redis established
Feb 19 19:30:27 unbound[1:0] notice: Connection to Redis established
Feb 19 19:30:27 unbound[1:0] notice: Connection to Redis established
Feb 19 19:30:27 unbound[1:0] warning: cachedb: serve-expired-reply-ttl is set but not working for data originating from the external cache; 0 TTL is used for those.
Feb 19 19:30:27 unbound[1:0] notice: init module 1: validator
Feb 19 19:30:27 unbound[1:0] notice: init module 2: iterator
Feb 19 19:30:27 unbound[1:0] info: start of service (unbound 1.19.1).
```

**Comment by jata1** [comment]
made the suggested change to 

`server:  module-config: "cachedb validator iterator"`

**Comment by madnuttah** [comment]
You'll be flashed about the performance, I promise.

**Comment by jata1** [comment]
Thank you @madnuttah and @JaneDilbert

**Comment by jata1** [comment]
Now I need to fix the ugly volume name for cachedb.d - what is happening here? I don't usually use portainer but can spin this up if it can help troubleshoot

**Comment by madnuttah** [comment]
Portainer isn't necessary but neat.

Try this in your compose:

```

...
  redis-socket:
    image: busybox
    container_name: redis-socket
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        chown -R 999:100 /usr/local/unbound/cachedb.d/ # Change group (:1000) to your used GID
        /bin/sh
    volumes:
       - cachedb.d:/symlinks/omv-system/appdata/unbound/cachedb.d:/usr/local/unbound/cachedb.d/ ### Changed 

...

volumes:
  cachedb.d:
...

```

**Comment by jata1** [comment]
I thought that was going to work as I can see the correct volume name being created when starting the compose but.

```
Feb 19 19:46:09 unbound[1:0] notice: init module 0: cachedb
Feb 19 19:46:09 unbound[1:0] notice: Redis initialization
Feb 19 19:46:09 unbound[1:0] error: failed to connect to redis server: No such file or directory
Feb 19 19:46:09 unbound[1:0] error: redis_init: failed to init redis
Feb 19 19:46:09 unbound[1:0] error: cachedb: could not init redis backend
Feb 19 19:46:09 unbound[1:0] error: module init for module cachedb failed
Feb 19 19:46:09 unbound[1:0] fatal error: failed to setup modules
```

**Comment by madnuttah** [comment]
Show me the cachedb-related part of your `unbound.conf` please.

**Comment by jata1** [comment]
```
cachedb:
  backend: redis
  redis-timeout: 100
  redis-expire-records: no
  redis-server-path: /usr/local/unbound/cachedb.d/redis.sock
```

**Comment by madnuttah** [comment]
ARGH, my bad!

...
  redis-socket:
    image: busybox
    container_name: redis-socket
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        chown -R 999:100 /usr/local/unbound/cachedb.d/ # Change group (:1000) to your used GID
        /bin/sh
    volumes:
       - cachedb.d:/usr/local/unbound/cachedb.d/ ### Changed again :)

...

volumes:
  cachedb.d:
...

My apologies.

**Comment by madnuttah** [comment]
ARGH, my bad!


```
...

  redis-socket:
    image: busybox
    container_name: redis-socket
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        chown -R 999:100 /usr/local/unbound/cachedb.d/ # Change group (:1000) to your used GID
        /bin/sh
    volumes:
       - cachedb.d:/usr/local/unbound/cachedb.d/ ### Changed again :)

...

volumes:
  cachedb.d:
...
```

My apologies.

**Comment by jata1** [comment]
same issue. I notice there are 2 volumes being created. one with nice name. the other ugly!

**Comment by JaneDilbert** [comment]
> ```
>     volumes:
>        - cachedb.d:/usr/local/unbound/cachedb.d/ ### Changed again :)
> ```

What's the entry in cachedb.d? I believe @jata1 mentioned it was empty (copied from the some example?)

**Comment by jata1** [comment]
@JaneDilbert - Thanks. We have it working with this config a few minutes ago. Just tiding up the name for the volume that is created

**Comment by madnuttah** [comment]
Please show me the relevant cachedb part from your `unbound.conf`

**Comment by jata1** [comment]
```
cachedb:
  backend: redis
  redis-timeout: 100
  redis-expire-records: no
  redis-server-path: /usr/local/unbound/cachedb.d/redis.sock
```

**Comment by madnuttah** [comment]
Doesn't look bad. What happens if you make a `docker compose down && docker-compose up-d`?

**Comment by jata1** [comment]
we had it working earlier. Now it looks like 2 volumes are being created. I thin the missing bit is mapping the volume to the host.

we changed the volume location to:

```
    volumes:
       - cachedb.d:/usr/local/unbound/cachedb.d/
```
 
but we still need it to point to /symlinks/omv-system/appdata/unbound/cachedb.d

but i'm not sure how

**Comment by madnuttah** [comment]
The config looks good as I can tell. Open Portainer and manually remove the volume, it should be flagged "unused". Can you see a volume named `cachedb.d`?

**Comment by jata1** [comment]
Thank you for all the help. I got it working again but there are 2 volumes created. One with a nice name and another one with long name

**Comment by madnuttah** [comment]
In Portainer you should see which container is connected to the non `cachedb.d` volume. Change the compose for that container then. You can also show me the relevant part of that container.

Edit: ...is connected to the non `cachedb.d` folder

**Comment by jata1** [comment]
it relates to the redis (unbound-db) container

```
 redis:
    container_name: unbound-db
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /symlinks/omv-system/appdata/unbound/redis.conf:/usr/local/etc/redis/redis.conf
    volumes_from:
      - redis-socket:rw
```

**Comment by madnuttah** [comment]
Weird, should work.

This is what I use:

```
 unbound-db:
    container_name: unbound-db
    image: redis:alpine
    mac_address: <The MAC>
    hostname: unbound-db
    domainname: <domain.suffix>
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /MOUNTPOINT/unbound-db/data:/data/
      - /MOUNTPOINT/unbound-db/redis.conf:/usr/local/etc/redis/redis.conf
      - /MOUNTPOINT/unbound-db/healthcheck.sh:/usr/local/sbin/healthcheck.sh:ro
    volumes_from:
      - unbound-db-socket:rw
    healthcheck:
      test: /usr/local/sbin/healthcheck.sh
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 30s
    depends_on:
      - unbound-db-socket
    networks:
      - docker-bridge
 
 
networks: 

  docker:
  ...
        
  docker-bridge:
  ...
        
volumes:
  cachedb.d:
```

I've made myself a healthcheck script, I'll upload it with a next update. It's recommended anyways.

Edit: removed environment as apparently not needed

**Comment by madnuttah** [comment]
Here it goes @jata1: 

```
#! /bin/sh

SOCKET=/usr/local/unbound/cachedb.d/redis.sock
if [[ ! -S "$SOCKET" ]];
then
    exit 1    
fi
```

**Comment by jata1** [comment]
Found the issue and fixed. The clue was thanks to @JaneDilbert in her first post. All running and tidy now.

startup log below and corrected compose for redis too - hope this helps other folks. The redis container was missing a volume mapping for the data directory

```
  redis:
    container_name: unbound-db
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /symlinks/omv-system/appdata/unbound/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /symlinks/omv-system/appdata/unbound/redis/data:/data
    volumes_from:
      - redis-socket:rw


```


```
Feb 19 22:32:40 unbound[1:0] notice: init module 0: cachedb
Feb 19 22:32:40 unbound[1:0] notice: Redis initialization
Feb 19 22:32:40 unbound[1:0] notice: Connection to Redis established
Feb 19 22:32:40 unbound[1:0] notice: Connection to Redis established
Feb 19 22:32:40 unbound[1:0] notice: Connection to Redis established
Feb 19 22:32:40 unbound[1:0] notice: Connection to Redis established
Feb 19 22:32:40 unbound[1:0] warning: cachedb: serve-expired-reply-ttl is set but not working for data originating from the external cache; 0 TTL is used for those.
Feb 19 22:32:40 unbound[1:0] notice: init module 1: validator
Feb 19 22:32:40 unbound[1:0] notice: init module 2: iterator
Feb 19 22:32:40 unbound[1:0] info: start of service (unbound 1.19.1).
Feb 19 22:32:41 unbound[1:2] info: generate keytag query _ta-4f66. NULL IN
```
