### ISSUE TITLE
unbound with redis cache does not start sucessfully on host server reboot

### ISSUE THREAD

**Issue by jata1** [madnuttah/unbound-docker#58]
Hello again. Thanks for helping me with my setup of unbound with redis. It all works fine when I start the containers/compose when my docker server/host is running.

If I restart the docker server I expect unbound to restart but it does not and I am not sure why. 

Here is my full compose file. I added dependencies that I thought would help but I still have this issue. 

```
version: '3.3'

services:
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    restart: unless-stopped
    depends_on:
      - unbound-db
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    networks:
      rpi5_macvlan:
        ipv4_address: "192.168.100.15"
    environment:
      ServerIP: 192.168.100.15
      TZ: ${TZ}
      UID: ${PUID}
      GID: ${PGID}
    volumes:
      - /symlinks/omv-system/appdata/unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw
      - /symlinks/omv-system/appdata/unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - /symlinks/omv-system/appdata/unbound/iana.d/:/usr/local/unbound/iana.d/:rw
      - /symlinks/omv-system/appdata/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - /symlinks/omv-system/appdata/unbound/zones.d/:/usr/local/unbound/zones.d/:rw
    volumes_from:
      - unbound-socket:rw
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s

  unbound-socket:
    image: busybox
    container_name: unbound-socket
    restart: unless-stopped
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        chown -R 999:100 /usr/local/unbound/cachedb.d/
        /bin/sh
    volumes:
      - cachedb.d:/usr/local/unbound/cachedb.d/
      
  unbound-db:
    container_name: unbound-db
    image: redis:alpine
    restart: unless-stopped
    depends_on:
      - unbound-socket
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /symlinks/omv-system/appdata/unbound/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /symlinks/omv-system/appdata/unbound/redis/data:/data
      - /symlinks/omv-system/appdata/unbound/redis/healthcheck.sh:/usr/local/sbin/healthcheck.sh:ro
    volumes_from:
      - unbound-socket:rw
    healthcheck:
      test: /usr/local/sbin/healthcheck.sh
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 30s

volumes:
  cachedb.d:

networks:
  rpi5_macvlan:
    name: rpi5_macvlan
    external: true
```
