### ISSUE TITLE
OCI runtime create failed: runc create failed

### ISSUE THREAD

**Issue by bunkerman** [madnuttah/unbound-docker#67]
Hi,

I  tried the image and it works with the minimal compose. I also extended it with redis and the proxy, this also works.
But if I use an unbound.conf (which I need for the cachedb module-config) with a mount on my nas it gives me the error "Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/unbound/sbin/unbound.sh": stat /usr/local/unbound/sbin/unbound.sh: no such file or directory: unknown". 
So I put the unbound.sh file in the mount, but then I get the error "/usr/local/sbin/unbound.sh: line 2: /usr/local/unbound/unbound.d/sbin/unbound-anchor: not found
/usr/local/sbin/unbound.sh: exec: line 3: /usr/local/unbound/unbound.d/sbin/unbound: not found".

I chowned the unbound folder with 1000:1000 and I'm using Portainer stacks, but I did try a docker compose file and it gives the same error.

Do you know what's causing this issue?

Thanks

**Comment by madnuttah** [comment]
Hey there and many thanks for contacting me with your issue. I guess something's not right with your `unbound.conf`. Please show us the file including your `docker-compose.yaml`. 

Thank you.

**Comment by bunkerman** [comment]
Thanks so much for looking into this:
docker compose
```
version: '3'

services:
  unbound:
    container_name: unboundstack
    image: madnuttah/unbound:latest
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    volumes:
      - /nasmount/unboundstack/unbound:/usr/local/unbound:rw
      - /nasmount/unboundstack/unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - /nasmount/unboundstack/unbound/log.d:/usr/local/unbound/log.d:rw
      - /nasmount/unboundstack/unbound/zones.d/:/usr/local/unbound/zones.d/:rw
      - /nasmount/unboundstack/unbound/sbin:/usr/local/unbound/sbin:ro
    environment:
      TZ: Europe/Berlin
      #UNBOUND_UID: 1000
      #UNBOUND_GID: 100
    restart: unless-stopped
    volumes_from:
      - unbound-db-socket:ro
   # depends_on:
   #   unbound-db:
   #     condition: service_healthy
   # healthcheck:
   #   test: /usr/local/unbound/sbin/healthcheck.sh
   #   interval: 60s
   #   retries: 5
   #   start_period: 15s
   #   timeout: 30s

  unbound-db-socket:
    image: busybox
    container_name: unbound-db-socket
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        chown -R 999:1000 /usr/local/unbound/cachedb.d/ # Change group (:1000) to your used GID
        /bin/sh
    restart: unless-stopped
    volumes:
       - /nasmount/unboundstack/redis/cachedb.d:/usr/local/unbound/cachedb.d
  unbound-db:
    image: 'redis:alpine'
    container_name: unbound-db
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /nasmount/unboundstack/redis/data:/data
      - /nasmount/unboundstack/redis/config:/usr/local/etc/redis
     # - /nasmount/unboundstack/redis/sbin:/usr/local/sbin:ro
    volumes_from:
      - unbound-db-socket:rw
    depends_on:
      - unbound-db-socket
   # healthcheck:
   #   test: /usr/local/sbin/healthcheck.sh
   #   interval: 10s
   #   retries: 5
   #   start_period: 5s
   #   timeout: 30s
    restart: unless-stopped
```

and the unbound conf is thge one published in your repo: https://github.com/madnuttah/unbound-docker/blob/main/unbound/root/usr/local/unbound/unbound.conf 

with unbound volumes commented out it works

**Comment by madnuttah** [comment]
Sure, happy to help! 

Your volumes ain't looking right, please try this (intendation may be off):

```
   volumes:
      - /nasmount/unboundstack/unbound.conf:/usr/local/unbound/unbound.conf:rw
      - /nasmount/unboundstack/conf.d/:/usr/local/unbound/conf.d/:rw
#      - /nasmount/unboundstack/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - /nasmount/unboundstack/zones.d/:/usr/local/unbound/zones.d/:rw
```

If you need the log, later touch a `unbound.log` in the `/../log.d/` folder and fix permissions and ownership.

Thank you.

**Comment by bunkerman** [comment]
doh, I'm feeling dumb right now :)
It works with the unbound.conf in place and written in the volume mount. I didn't used it, because I thought Portainer could only handle folders...
 Also the healthchecks do work.
my unbound log now shows:

```
May 23 21:50:36 unbound[1:0] notice: init module 0: cachedb

May 23 21:50:36 unbound[1:0] notice: init module 1: validator

May 23 21:50:36 unbound[1:0] notice: init module 2: iterator

May 23 21:50:36 unbound[1:0] warning: auth zone .: ZONEMD verification failed: verify DNSKEY RRset with trust anchor failed

May 23 21:50:36 unbound[1:0] info: start of service (unbound 1.20.0).
```

In your docs you write that in the logs should be

```
Feb 18 22:01:02 unbound[1:0] notice: Redis initialization 
Feb 18 22:01:02 unbound[1:0] notice: Connection to Redis established
```

So I guess the connection is not established?

(the redis healthcheck gives a " Unix Socket found")

**Comment by madnuttah** [comment]
No problem at all! Looks almost fine so far, redis is connected as well. We've had a similar warning message in `https://github.com/madnuttah/unbound-docker/issues/19`, can you verify this please? Do you use a Raspberry Pi?

**Comment by madnuttah** [comment]
No problem at all! We've had a similar warning message in https://github.com/madnuttah/unbound-docker/issues/19, can you verify this please? Do you use a Raspberry Pi?

We'll check redis later, it would be a better idea to get the basics running first so I'd suggest to comment out the it's section in your compose file.

**Comment by bunkerman** [comment]
I added "- nas/unboundstack/unbound/iana.d/:/usr/local/unbound/iana.d/:rw" and put the root.zone file in there and that error is gone.
I'm using OpenMediaVault (Debian) with a Xeon CPU.

**Comment by bunkerman** [comment]
my updated compose file

```
version: '3'
networks:
  wirehole:
    driver: macvlan
    external: true
services:
  unbound:
    container_name: unboundstack
    image: madnuttah/unbound:latest
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    volumes:
      - /nasmount/unboundstack/unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw
      - /nasmount/unboundstack/unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - /nasmount/unboundstack/unbound/log.d/:/usr/local/unbound/log.d/:rw
      - /nasmount/unboundstack/unbound/zones.d/:/usr/local/unbound/zones.d/:rw
      - /nasmount/unboundstack/unbound/iana.d/:/usr/local/unbound/iana.d/:rw
      - /nasmount/unboundstack/unbound/sbin/healthcheck.sh:/usr/local/unbound/sbin/healthcheck.sh:ro
    environment:
      TZ: Europe/Berlin
      #UNBOUND_UID: 1000
      #UNBOUND_GID: 100
    restart: unless-stopped
    volumes_from:
      - unbound-db-socket:ro
    networks:
      wirehole:
        ipv4_address: xxx
    depends_on:
      unbound-db:
        condition: service_healthy
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s

  unbound-db-socket:
    image: busybox
    container_name: unbound-db-socket
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        chown -R 999:1000 /usr/local/unbound/cachedb.d/ # Change group (:1000) to your used GID
        /bin/sh
    restart: unless-stopped
    volumes:
       - /nasmount/unboundstack/redis/cachedb.d/:/usr/local/unbound/cachedb.d/
  unbound-db:
    image: 'redis:alpine'
    container_name: unbound-db
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /nasmount/unboundstack/redis/data/:/data/
      - /nasmount/unboundstack/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - /nasmount/unboundstack/redis/sbin/healthcheck.sh:/usr/local/sbin/healthcheck.sh:ro
    volumes_from:
      - unbound-db-socket:rw
    depends_on:
      - unbound-db-socket
    healthcheck:
      test: /usr/local/sbin/healthcheck.sh
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 30s
    restart: unless-stopped
```

**Comment by madnuttah** [comment]
The compose looks good at first glance. Did you put this

```
...
server:
  module-config: "cachedb validator iterator"
...
cachedb:
  backend: redis
  redis-timeout: 100
  redis-expire-records: no
  redis-server-path: /usr/local/unbound/cachedb.d/redis.sock
```

into your unbound.conf? See https://github.com/madnuttah/unbound-docker/blob/main/doc/DETAILS.md#cachedb-redis

**Comment by bunkerman** [comment]
the first part is in the unbound.conf and it gets loaded, because I see that in the log
and the second part 
```
cat cachedb.conf
cachedb:
  backend: redis
  redis-timeout: 100
  redis-expire-records: no
  redis-server-path: /usr/local/unbound/cachedb.d/redis.sock
```
I have tried it with TCP connections and that works out of the box, but that socket thing is new to me.
Any special permissions needed?
redis folder
```
drwxr-xr-x 2 root                  root 4096 May 24 10:27 config
drwxr-xr-x 2 openmediavault-webgui root 4096 May 24 11:03 data
drwxr-xr-x 2 root                  root 4096 May 23 21:42 sbin
drwxr-xr-x 2 root                  root 4096 May 24 10:40 sys
```
busybox folder
`drwxr-xr-x 2 openmediavault-webgui sftp-access 4096 May 24 11:04 cachedb.d`

the openmediavault-webgui should be 999 and normally my docker user is 1000:100

**Comment by madnuttah** [comment]
Oh yes, there were the log entries. Sorry, I didn't see it first. 

The redis permissions should be 999:1000. 999 is the redis uid and 1000 the _unbound gid.

**Comment by madnuttah** [comment]
Could you run this command please?

`docker exec -ti unboundstack sh -c "cd /usr/local/unbound/cachedb.d/ && echo *"`

Do you see a `redis.sock` file?

**Comment by bunkerman** [comment]
I get exactly that output

**Comment by madnuttah** [comment]
In the data folder on your volume, do you see a `.rdb` file, eventually even growing?

**Comment by bunkerman** [comment]
in the data folder is

```
redis/data# ls -l
total 4
-rw------- 1 openmediavault-webgui sftp-access 88 May 24 11:03 dump.rdb
```

but I think it was just created

**Comment by madnuttah** [comment]
Technically, everything looks fine in aspect of what I have seen yet. You could upload a zip with all of your configs if you want me to take a look at the whole thing. Also, you can ramp up unbound's verbosity to see more things happen in the background.

Edit: what's the `unbound-db` log saying?

**Comment by bunkerman** [comment]
Thank you so much for taking your time and helping me out!
It now works! Strangely after several container restarts, it worked. After you suggested to turn up the verbosity, I saw that the config changes wouldn't be recognized. I completely deleted the containers and images and added 

```
cachedb:
  backend: redis
  redis-timeout: 100
  redis-expire-records: no
  redis-server-path: /usr/local/unbound/cachedb.d/redis.sock
```
directly to the unbound.conf
So I have to check why the cachedb.conf is not recognized.
