### ISSUE TITLE
dockerd error message

### ISSUE THREAD

**Issue by bunkerman** [madnuttah/unbound-docker#82]
Hello,

I get constant log messages like this:
`"dockerd[2252]: time="2024-12-02T14:20:03.634699510+01:00" level=error msg="collecting stats for container /unbound-db-socket: NotFound: container \"dd1927ebed109c6fba6db549639bf299eb7b09a4144bee263990eea495013a04\" in namespace \"moby\": not found"`

Do you know whats causing this?

The Pihole-Unbound-Redis-Busybox Stack is working as far as I can tell.

**Comment by madnuttah** [comment]
Hi!

It seems like a container can't be found, could you do a `docker compose down` and then `docker compose up`?

**Comment by bunkerman** [comment]
ok, I restarted the stack and now get
` dockerd[2252]: time="2024-12-02T16:16:59.630838832+01:00" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:127.0.0.1:45262" dns-server="udp:127.0.0.53:53" error="read udp 127.0.0.1:45262->127.0.0.53:53: i/o timeout" question>`

`dockerd[2252]: time="2024-12-02T16:20:40.018057083+01:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers"`

**Comment by madnuttah** [comment]
The message states that the resolver listening on `127.0.0.53:53` isn't answering.

Have you tried from scratch first? If so, I'd need your config files (yaml, conf including your docker host's resolv.conf) to see what's wrong with your setup.

Thanks.

**Comment by bunkerman** [comment]
So after the restart the error in the logs is gone: `level=error msg="collecting stats for container /unbound-db-socket`
but then the logs get flooded with
 `dockerd[2252]: time="2024-12-02T22:48:43.139754108+01:00" level=info msg="ignoring event" container=4f687a930803af2615734f8acee957aee>`
`dockerd[2252]: time="2024-12-02T22:49:44.202644852+01:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. U>`

via docker ps I saw that the busybox container is constantly restarted.

docker-compose.yaml
```
version: "3.8"
networks:
  wirehole:
    driver: macvlan
    external: true
services:
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    volumes:
      - /etc/localtime:/etc/localtime
      - /portainer/Files/unboundstack/unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw
      - /portainer/Files/unboundstack/unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - /portainer/Files/unboundstack/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - /portainer/Files/unboundstack/unbound/zones.d/:/usr/local/unbound/zones.d/:rw
      - /portainer/Files/unboundstack/unbound/iana.d/:/usr/local/unbound/iana.d/:rw
      - /portainer/Files/unboundstack/unbound/sbin/healthcheck.sh:/usr/local/unbound/sbin/healthcheck.sh:ro
    environment:
      TZ: Europe/Berlin
      UNBOUND_UID: 1000
      UNBOUND_GID: 100
      ENABLE_STATS: false
      EXTENDED_HEALTHCHECK: false
    restart: unless-stopped
    volumes_from:
      - unbound-db-socket:ro
    networks:
      wirehole:
        ipv4_address: 192.168.0.242
    depends_on:
      unbound-db:
        condition: service_healthy
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    environment:
      WEBPASSWORD: xxx
      TZ: Europe/Berlin
      PIHOLE_DNS_: 192.168.0.242#5335
    volumes:
      - /portainer/Files/pihole/etc-pihole:/etc/pihole
      - /portainer/Files/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime
    depends_on:
      unbound:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
    networks:
      wirehole:
        ipv4_address: 192.168.0.241
  unbound-db-socket:
    image: busybox
    container_name: unbound-db-socket
    init: true
    tty: true
    command: /bin/sh -c "chown -R 999:100 /usr/local/unbound/cachedb.d/"
    restart: unless-stopped
    volumes:
      - /portainer/Files/unboundstack/busybox/cachedb.d/:/usr/local/unbound/cachedb.d/
      - /etc/localtime:/etc/localtime
  unbound-db:
    image: redis:alpine
    container_name: unbound-db
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /portainer/Files/unboundstack/redis/data/:/data/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone:ro
      - /portainer/Files/unboundstack/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - /portainer/Files/unboundstack/redis/sbin/healthcheck.sh:/usr/local/sbin/healthcheck.sh:ro
      - /portainer/Files/unboundstack/redis/sys/sysctl.conf:/etc/sysctl.conf
    volumes_from:
      - unbound-db-socket:rw
    depends_on:
      - unbound-db-socket
    restart: unless-stopped
    healthcheck:
      test: /usr/local/sbin/healthcheck.sh
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 30s
```

My docker user is 1000:100, should the chown command also be that?
