### ISSUE TITLE
[Question] unbound-db-socket exited with code 0

### ISSUE THREAD

**Issue by MijnUsername** [madnuttah/unbound-docker#91]
I've modified https://github.com/madnuttah/unbound-docker/blob/main/doc/examples/docker-compose-madnuttah.yaml for my situation;

```
services:
  pihole:
    container_name: pihole-madnuttah
    image: pihole/pihole:latest
    hostname: pihole
    domainname: facility.private
    mac_address: DC:BD:99:D2:4F:CB
    user: 1000:1000
    depends_on:
      unbound-madnuttah:
        condition: service_healthy
    cap_add:
      - NET_BIND_SERVICE
    networks:
      subnet-2:
        ipv4_address: 192.168.2.24
      bridge:
        ipv4_address: 172.17.0.2
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      FTLCONF_LOCAL_IPV4: 192.168.2.24
      VIRTUAL_HOST: pihole.facility.private
      FTLCONF_webserver_api_password:
      WEBUIBOXEDLAYOUT: boxed
      TZ: "Europe/Amsterdam"
      CORS_HOSTS: facility.private
      PIHOLE_DNS_1: 192.168.2.25#53
      DNSSEC: "true"
      IPv6: "false"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      REV_SERVER: "false"
      DNSMASQ_LISTENING: all
      SKIPGRAVITYONBOOT: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/madnuttah/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/:rw
      - /home/pi/madnuttah/pihole/etc/lighttpd/pihole.pem:/etc/lighttpd/pihole.pem:ro
      - /home/pi/madnuttah/pihole/etc/lighttpd/pihole.key:/etc/lighttpd/pihole.key:ro
      - /home/pi/madnuttah/pihole/etc/lighttpd/root_ca.pem:/etc/lighttpd/root_ca.pem:ro
      - /home/pi/madnuttah/pihole/etc/lighttpd/external.conf:/etc/lighttpd/conf-enabled/external.conf:rw
      - /home/pi/madnuttah/pihole/etc/pihole/:/etc/pihole/:rw
      - /home/pi/madnuttah/pihole/etc/hosts.list:/etc/hosts:rw
      - /home/pi/madnuttah/pihole/etc/resolv.conf:/etc/resolv.conf:rw
      - /home/pi/madnuttah/pihole/etc/hostname:/etc/hostname:rw
    restart: always

  unbound-madnuttah:
    container_name: unbound-madnuttah
    image: madnuttah/unbound:latest
    mac_address: 88:AF:DA:C9:ED:A5
    user: 1000:1000
    hostname: unbound-madnuttah
    domainname: facility.private
    networks:
      subnet-2:
        ipv4_address: 192.168.2.25
    environment:
      TZ: "Europe/Amsterdam"
      UNBOUND_UID: 1000
      UNBOUND_GID: 1000
      HEALTHCHECK_PORT: 5335
      EXTENDED_HEALTHCHECK: true
      EXTENDED_HEALTHCHECK_DOMAIN: "nlnetlabs.nl"
      ENABLE_STATS: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/madnuttah/unbound/sbin/healthcheck.sh:/usr/local/unbound/sbin/healthcheck.sh:ro
      - /home/pi/madnuttah/unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw
      - /home/pi/madnuttah/unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - /home/pi/madnuttah/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - /home/pi/madnuttah/unbound/log.d/unbound-stats.log:/usr/local/unbound/log.d/unbound-stats.log:rw
      - /home/pi/madnuttah/unbound/zones.d/:/usr/local/unbound/zones.d/:rw
      - cachedb.d:/usr/local/unbound/cachedb.d/
    restart: always
    depends_on:
      unbound-db:
        condition: service_healthy
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 3
      start_period: 5s
      timeout: 15s

  unbound-db-socket:
    image: busybox
    container_name: unbound-db-socket
    init: true
    tty: true
    command: /bin/sh -c "chown -R 999:1000 /usr/local/unbound/cachedb.d/"
    volumes:
       - cachedb.d:/usr/local/unbound/cachedb.d/
    networks:
       - bridge

  unbound-db:
    container_name: unbound-db
    image: redis:alpine
    mac_address: 4E:A5:D9:0B:CF:68
    hostname: unbound-db
    domainname: facility.private
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/pi/madnuttah/unbound-db/data:/data/
      - /home/pi/madnuttah/unbound-db/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/pi/madnuttah/unbound-db/sysctl.conf:/etc/sysctl.conf
      - /home/pi/madnuttah/unbound-db/healthcheck.sh:/usr/local/sbin/healthcheck.sh:ro
      - cachedb.d:/usr/local/unbound/cachedb.d/
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 15s
    depends_on:
      - unbound-db-socket
    networks:
      - bridge

networks:
  subnet-2:
    external: true

  bridge:

volumes:
  cachedb.d:
```

**To Reproduce**
1. First I ran the complete docker-compose.yml by executing sudo docker compose up
2. Then it fails at 
```
[+] Running 2/2
 ✔ Container unbound-db         Created                                                                                   0.0s
 ✔ Container unbound-db-socket  Recreated                                                                                 0.1s
Attaching to pihole-madnuttah, unbound-db, unbound-db-socket, unbound-madnuttah
unbound-db-socket exited with code 0
unbound-db         | 1:C 10 Mar 2025 22:27:42.282 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
unbound-db         | 1:C 10 Mar 2025 22:27:42.283 * Redis version=7.4.2, bits=64, commit=00000000, modified=0, pid=1, just started
unbound-db         | 1:C 10 Mar 2025 22:27:42.283 * Configuration loaded
unbound-db         | 1:M 10 Mar 2025 22:27:42.284 * monotonic clock: POSIX clock_gettime
unbound-db         | 1:M 10 Mar 2025 22:27:42.286 * Running mode=standalone, port=0.
unbound-db         | 1:M 10 Mar 2025 22:27:42.287 # Failed opening Unix socket: bind: Permission denied
unbound-db exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container unbound-db exited (1)
```
4. Then I isolated the failing part for troubleshooting 
```
services:
  unbound-db-socket:
    image: busybox
    container_name: unbound-db-socket
    init: true
    tty: true
    command: [/bin/sh -c "chown -R 999:1000 /usr/local/unbound/cachedb.d/"]
    volumes:
       - cachedb.d:/usr/local/unbound/cachedb.d
    networks:
       - bridge

volumes:
  cachedb.d:
  
networks:
  bridge:
```
5. and ran sudo docker compose up again, the following happened 
```
[+] Running 2/2
 ✔ Network pi_bridge            Created                                                                                   0.2s
 ✔ Container unbound-db-socket  Created                                                                                   0.1s
Attaching to unbound-db-socket
unbound-db-socket  | [FATAL tini (7)] exec /bin/sh -c "chown -R 999:1000 /usr/local/unbound/cachedb.d/" failed: No such file or directory
unbound-db-socket exited with code 127
```

**Expected behavior**
I'm not sure what's causing the error message. Changing the command parameter to 
```
command: 
       - /bin/sh
       - -c
       - |
       - "chown -vR 999:1000 /usr/local/unbound/cachedb.d/"
```
makes unbound-db-socket exit with code 0
```
[+] Running 1/1
 ✔ Container unbound-db-socket  Recreated                                                                                 0.1s
Attaching to unbound-db-socket
unbound-db-socket exited with code 0
```

**Please complete the following information:**
 - Device: [e.g. Raspberry Pi 4]
 - System: 64-bit
- Debian version: 12 (bookworm)
 - Architecture: arm64
